config/routes.rb
Qb::Application.routes.draw do
  
  resources :questions do
    collection do
      post 'import'
    end
  end

  resources :tests do 
    member do
      get 'sample'
      get 'conduct'
      post 'conduct'
    end
  end

  get '/schedules' => "test_papers#index"

  get  '/mytest/:pin'    => "candidates#mytest"

  delete '/attachments/:id' => 'attachments#delete'

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :statement

  belongs_to :submitter, :class_name => 'User'
  
  can_have_attachments :max => 5

  resourcify

  concerned_with :searchable, :taggable, :to_txt, :objective, :natures

  attr_accessor :marks

  def text
    Nokogiri::HTML(statement).text
  end
  
  def title
    "#{self.text[0..200]} ..."
  end

  def self.available_for_test
    topics.product(complexities, natures).collect do |topic_complexity_nature|
      topic_complexity_nature << tagged_with(topic_complexity_nature).count
    end
  end
end

app/models/question/importer.rb
require 'rubyXL'

class QuestionImporter
  MIN_SIZE = 7168          #7Kb
  MAX_SIZE = 10485760      #10Mb

  def current_user= user
    @current_user = user
  end
  
  def initialize file=nil, current_user=nil
    #@upload_questions_moderator_id = nil
    #@upload_questions_status = 'moderated'
    @failed_upload_question_numbers = []
    @successfuly_upload_question_numbers = []
    @successfuly_upload_questions = []
    @current_user = current_user

    validate_and_parse file, current_user if file and current_user
  end

  def validate_and_parse file, current_user
    if file.blank?
      @upload_error = 'Blank file'
      return
    end
    
    unless (File.extname(file.original_filename).eql? '.xlsx')
      @upload_error = 'Invalid file'
      return
    end

    file_path = save_file_on_disk file
    return unless file_path

    if File.size(file_path) < MIN_SIZE
      @upload_error = 'Blank file'
      File.delete file_path
      return
    end

    if File.size(file_path) > MAX_SIZE
      @upload_error = 'File size too large, allowed upto 10 MB only'
      File.delete file_path
      return
    end
    
    unless process_questions_xls file_path
      File.delete file_path
      return
    end
    
    File.delete file_path
  end

  attr_reader :upload_error, :failed_upload_question_numbers, 
  :successfuly_upload_question_numbers, :successfuly_upload_questions

  def save_file_on_disk(file)
    begin
      input_path = Rails.root.join("tmp/imported_questions_files/").to_s
      filename = Time.now.strftime("%Y%m%d%H%M%S") + '_' + file.original_filename.gsub(' ','_')
      file_path = input_path + filename
      File.open(file_path, "wb") { |disk_file| disk_file.write( file.read)}
    rescue
      @upload_error = 'Could not write on disk'
      return
    end
    file_path
  end

  def process_questions_xls(file_path)
    begin
      xlsx = RubyXL::Parser.parse file_path
      first_sheet = xlsx[0].extract_data
    rescue Exception => e
      @upload_error = 'Does not seem to be a valid xlsx.'
      puts "  upload error: #{e.message}"
      return
    end

    return unless header_checks_ok? first_sheet[0]

    first_sheet[1..-1].each do | row|
      process_question row
    end
  end

  def header_checks_ok? columns
    if columns.size < 10
      @upload_error = '10 header columns expected'
      return
    end

    expected_headers = ['S. No.', 'Topic', 'Complexity Level', 'Question','Answer A','Answer B','Answer C','Answer D','Answer E','Correct Answer']

    expected_headers.each_with_index do |expected_header, index|
      unless ( columns[index].casecmp(expected_header) == 0)
        @upload_error = "Invalid column \"#{columns[index]}\", expected \"#{expected_header}\""
        return
      end
    end
    
    true
  end

  def process_question(columns)
    row_count = columns[0].to_i
    return unless row_count
    return if row_count < 1

    topic = columns[1].to_s.strip
    if topic.length < 2
      @failed_upload_question_numbers <<  { :number => row_count, :reason => 'Invalid topic'}
      return
    end

    #    unless Question::Topics.include? topic
    #      @failed_upload_question_numbers <<  { :number => row_count, :reason => 'Invalid topic'}
    #      return
    #    end

    complexity = columns[2].to_s.strip
    if complexity.length < 2
      @failed_upload_question_numbers <<  { :number => row_count, :reason => 'Invalid topic'}
      return
    end
    
    #    unless Question::Complexities.include? complexity
    #      @failed_upload_question_numbers << { :number => row_count, :reason => 'Invalid complexity level'}
    #      return
    #    end
    
    statement_body = columns[3].to_s
    if statement_body.nil? or (statement_body.to_s.strip.size < 4)
      @failed_upload_question_numbers << { :number => row_count, :reason => 'Invalid question statement'}
      return
    end

    answers_statements = []
    expected_right_answer = ['A', 'B', 'C', 'D', 'E']
    available_answers = []
    4.upto(8) do |index|
      unless columns[index].nil?
        if columns[index].to_s.strip.size > 0
          answers_statements << columns[index]
          available_answers << expected_right_answer.at( index-4)
        end
      end
    end

    if answers_statements.size < 2
      @failed_upload_question_numbers << { :number => row_count, :reason => 'Minimum 2 answers expected'}
      return
    end

    if columns[9].to_s.strip.size < 1
      @failed_upload_question_numbers <<  { :number => row_count, :reason => 'Correct answer missing'}
      return
    end

    correct_answers = columns[9].to_s.upcase.split(',').to_set
    unless correct_answers.subset?(available_answers.to_set)
      @failed_upload_question_numbers << { :number => row_count, :reason => 'Invalid correct answer'}
      return
    end

    objective_options = []
    answers_statements.each_with_index do |answer_option, index|

      #      if (answer_option.class == Spreadsheet::Formula)
      #        statement = (answer_option.value == true) ? 'true' : 'false'
      #      elsif (answer_option.class == TrueClass)
      #        statement = 'true'
      #      elsif (answer_option.class == FalseClass)
      #        statement = 'false'
      #      else
      #        statement = answer_option
      #      end
      statement = answer_option

      is_correct = correct_answers.include? available_answers[index]

      objective_options << { :statement => statement, :is_correct => is_correct}
    end

    question = Question.new :complexity_list => complexity, :topic_list => topic, :nature_list => 'Objective'
    question.statement = statement_body
    question.submitter = @current_user
    question.assign_objective_options objective_options

    if question.save
      @successfuly_upload_question_numbers << row_count
      @successfuly_upload_questions << question
      
    else
      question.errors.full_messages.each do |error|
        @failed_upload_question_numbers << { :number => row_count, :reason => error}
      end
    end
  end
end

app/models/question/natures.rb
class Question < ActiveRecord::Base
  Natures = ['Subjective', 'Objective']

  def is_objective?
    self.nature=='Objective'
  end

  def is_subjective?
    self.nature=='Subjective'
  end
end

app/models/question/objective.rb
class Question < ActiveRecord::Base
  has_many :objective_options

  def options
    return unless is_objective?
    
    objective_options.select{ |option| option.statement  and option.statement .strip.length > 0 }
  end

  def validate_options options
    true
  end

  def update_objective_options options
    return objective_options.destroy unless options
    return unless validate_options options

    options = options.values if options.is_a? Hash
    options.reverse!

    self.objective_options.each do |existing|
      updated_one = options.pop

      if updated_one
        existing.statement  = updated_one[:statement]
        existing.is_correct = updated_one[:is_correct]
        existing.save
      else
        existing.destroy
      end
    end

    options.each do |new_one|
      objective_options.create new_one
    end
  end

  def assign_objective_options options
    return objective_options.destroy unless options
    return unless validate_options options

    options = options.values if options.is_a? Hash
    options.reverse!

    objective_options.each do |existing|
      updated_one = options.pop

      if updated_one
        existing.statement  = updated_one[:statement]
        existing.is_correct = updated_one[:is_correct]
        #existing.save
      else
        existing.destroy
      end
    end

    options.each do |new_one|
      objective_options.new new_one
    end
  end
end

app/models/question/searchable.rb
class Question < ActiveRecord::Base
  attr_accessible :delta
  define_index do
    indexes statement
    set_property :delta => true
  end
end

app/models/question/taggable.rb
class Question < ActiveRecord::Base
  acts_as_taggable
  
  acts_as_taggable_on :topics
  acts_as_taggable_on :complexities
  acts_as_taggable_on :natures

  attr_accessible :topic_list
  attr_accessible :complexity_list
  attr_accessible :nature_list

  def self.topics
    top_topics topic_counts.size
  end

  def self.topic_names
    topics.map(&:name)
  end

  def self.complexities
    top_complexities complexity_counts.size
  end

  def self.complexity_names
    complexities.map(&:name)
  end

  def self.natures
    top_natures nature_counts.size
  end

  def self.nature_names
    natures.map(&:name)
  end
  
  def topic
    topic_list.first
  end

  def complexity
    complexity_list.first
  end

  def nature
    nature_list.first
  end
end

app/models/question/to_txt.rb
class Question < ActiveRecord::Base
  def to_txt
    text_answer = ''
    
    option_labels = ['a', 'b', 'c', 'd', 'e']
    str = "\n#{text}\n\n Options:\n\n"
    objective_options.each_with_index do |option, index|
      str << "(#{option_labels[index]})\n#{option.to_txt}\n\n"
      
      text_answer << "#{option_labels[index]}, " if option.is_correct?
    end
    str << "\n"

    [str, text_answer]
  end
end

class Array
  def text_format
    text_answers = ''
    text = ''
    
    compact.each_with_index do |question, index|
      text << "\n"
      text << "(#{index+1})"
      question_text, question_answer = question.to_txt
      text << question_text
      text << "\n"

      text_answers << "(#{index+1}) #{question_answer}"
    end

    text << "\n"*80
    text << "Answers:\n"
    text << "-"*80
    text << "\n"
    text << text_answers
    text << "\n"
    text << "-"*80
    text << "\n"*10

    text
  end
end

app/models/questions/txt_formattable.rb
module TxtFormattable
  def text
    text_answer = ''
    
    option_labels = ['a', 'b', 'c', 'd', 'e']
    str = "\n#{self.text_body}\n\n Options:\n\n"
    self.objective_options.each_with_index do |option, index|
      str << "(#{option_labels[index]})\n#{option.text}\n\n"
      
      text_answer << "#{option_labels[index]}, " if option.is_correct?
    end
    str << "\n"

    [str, text_answer]
  end
end

class Array
  def text_format
    text_answers = ''
    text = ''
    
    self.each_with_index do |question, index|
      text << "\n"
      text << "(#{index+1})"
      question_text, question_answer = question.text
      text << question_text
      text << "\n"

      text_answers << "(#{index+1}) #{question_answer}"
    end

    text << "\n"*80
    text << "Answers:\n"
    text << "-"*80
    text << "\n"
    text << text_answers
    text << "\n"
    text << "-"*80
    text << "\n"*10

    text
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :question
  skip_before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :validate_tags, :only => [:create, :update]

  def index
    tags = filter_tags

    # http://stackoverflow.com/questions/2082399/thinking-sphinx-and-acts-as-taggable-on-plugin

    @questions = Question.tagged_with(tags, :match_all => false).page(@page).per(@per_page) unless tags.blank?
    @questions ||= Question.page(@page).per(@per_page)

    respond_to do |format|
      format.html # index.html.erb
      format.text { send_data @questions.text_format, :filename => "#{Time.now.utc.to_s.gsub('-', '').gsub(':', '').delete(' ')}_questions_#{tags.join('_')}.txt" }
    end
  end

  def show
  end

  def new
  end

  def create
    @question.submitter = current_user
    @question.assign_attributes params[:question]
    @question.topic_list = params[:question][:topic_list] unless params[:question][:topic_list].blank?
    @question.assign_objective_options params[:objective_options]

    if @question.save_attachments(params[:attachment]) and @question.save!
      redirect_to @question, :notice => "Successfully created question."

    else
      @question.errors[:base] << @attachments_errors
      render :new
    end
  end

  def edit
  end

  def update
    if @question.submitter != current_user
      flash[:error] = "For now, only owner can edit this."
      render :edit
      return
    end

    @question.assign_attributes params[:question]
    @question.topic_list = params[:question][:topic_list] unless params[:question][:topic_list].blank?
    @question.update_objective_options params[:objective_options]
    
    @question.assign_attributes :delta => true
    
    if @question.save_attachments(params[:attachment]) and @question.update_attributes(params[:statement]) and @question.save
      redirect_to @question, :notice  => "Successfully updated question."

    else
      @question.errors[:base] << @attachments_errors
      render :edit
    end
  end

  def destroy
    #@question = Question.find_by_id params[:id]
    #@question.destroy
    redirect_to questions_url, :notice => "feature inactive."
  end

  def import
    if request.post?
      importer = QuestionImporter.new params[:questions_file], current_user

      @upload_error = importer.upload_error
      @failed_upload_question_numbers = importer.failed_upload_question_numbers
      @successfuly_upload_question_numbers = importer.successfuly_upload_question_numbers
      @questions = importer.successfuly_upload_questions
      
      if not @upload_error
        render :index, :notice => 'Questions uploaded!'

      else
        @questions = Question.page(@page).per(@per_page)
        flash[:error] = "Questions upload failed: #{@upload_error}"
        render :index
      end
    end
  end

  private

  def validate_tags
    params[:question][:topic_list] = params[:other_topic] if params[:question][:topic_list]=='Other'
    params[:question].delete :topic_list if params[:question][:topic_list].downcase.include? 'other'
  end

  def filter_tags
    tags = []
    tags << params[:complexity].to_s  unless params[:complexity].blank?
    tags << params[:topic].to_s       unless params[:topic].blank?
    tags << params[:search].to_s      unless params[:search].blank?
    tags = tags.collect{ |tag| tag.downcase }
    tags = tags.uniq.compact
  end

  def question
    @question ||= Question.find_by_id(params[:id]) || Question.new
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def render_upload_status
    return unless @failed_upload_question_numbers
    
    html = ""
    
    html << "Successfuly uploaded #{@successfuly_upload_question_numbers.size} questions <br/><br/>" if @successfuly_upload_question_numbers.size > 0

    if @failed_upload_question_numbers.size > 0
      html << "<div id='errorExplanation' class='errorExplanation'>"
      html << "<h2>Following #{@failed_upload_question_numbers.size} questions were not uploaded</h2><p></p>"
      html << "<ul>"
      
      @failed_upload_question_numbers.each do |error|
        html << "<li>#{error[:number]}: #{error[:reason]}</li>"
      end
      html << "</ul><div class=\"clear\"> </div></div>"
    end
    
    html
  end
  
end

app/views/questions/_form.html.erb
<%= form_for @question, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <%= raw errors_for @question %>
    <%= (input_multiline_text 'statement', { :textarea_cols => 80, :autofocus => 'autofocus', :label => '', :html => " autofocus='autofocus' width='96%' height='300px'"}).html_safe  %>

    <div class="control-group">
      <table>
        <tr>

          <td class="span6">
            <!--<#% #raw input_attachments :object => 'statement' %>-->
          </td>

          <td valign="top">
            <div class="control-group">
              <table style="float:right;">
                <tr>
                  <td>Complexity: </td>
                  <td>
                    <%= select("question", "complexity_list", Question.complexities.collect{|complexity| [complexity.name, complexity.name]}) %>
                  </td>
                </tr>

                <tr>
                  <td>Topic: </td>
                  <td>
                    <%= select("question", "topic_list", Question.topics.collect{|topic| [topic.name, topic.name]} + [['Other', 'Other']], {}, :onchange => 'topic_changed(this.value);') %>
                  </td>
                </tr>

                <tr>
                  <td>
                  </td>
                  <td>
                    <input type="text" name="other_topic" id="other_topic" value="Enter other topic"/>
                  </td>
                </tr>
              </table>
            </div>
          </td>

        </tr>
      </table>
    </div>

    <div class="control-group">
      <div class="controls">
        This question of type <%= select("question", "nature_list", Question::Natures.collect{|val| [val, val]}, {}, :onchange => 'nature_changed(this.value);') %>
      </div>
    </div>

    <div class="control-group" id="objective_options" style="display:none;">
      <div class="controls">
        <%= render :partial => 'objective' %>
      </div>
    </div>

  </fieldset>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'Cancel', questions_path, :class => 'btn' %>
  </div>

<% end %>




<script type="text/javascript">
  function nature_changed(nature){
    if (nature=='Objective'){
      //$("#objective_options").show();
      $("#objective_options").show('highlight',null,'slow');
    }
    else{
      $("#objective_options").hide('fade',null,'slow');
    }
  }
  nature_changed($('#question_nature_list').val());

  function topic_changed(topic){
    if (topic==='Other'){
      $("#other_topic").show('highlight',null,'slow');
    }
    else{
      $("#other_topic").hide('fade',null,'slow');
    }
  }
  topic_changed($('#question_topic_list').val());

</script>

app/views/questions/_objective.html.erb
<%= raw input_answers 0, { :mandatory => true} -%>
<%= raw input_answers 1, { :mandatory => true} -%>
<%= raw input_answers 2  -%>
<%= raw input_answers 3 -%>
<%= raw input_answers 4 -%>

app/views/questions/edit.html.erb
<div class="control-group">
  <div class="controls">
    <h4 style="color: #444;margin-left: 160px;">Edit this question</h4>
  </div>
</div>
<br/>

<%= render :partial => 'form', :locals => { :form_action_title => 'Edit' } %>

app/views/questions/index.html.erb
<div class="well" style="background-color: white;">

  <table class="table table-striped">
    <thead>
      <tr>
        <th style="width:70%;">
          <!--<input id="question_search" type="text" value="<%= params[:search] %>" onkeyup="if(check_for_enter_pressed(event)) tagged_questions();" autofocus="autofocus"/>-->
        </th>
        <th>
          <%= select("question", "complexity_list", Question.complexities.collect{|complexity| [complexity.name, complexity.name]}, {:prompt => 'Any', :selected => params[:complexity]}, :onchange => 'tagged_questions();', :style => 'width:100px;') %>
        </th>
        <th>
          <%= select("question", "topic_list", Question.topics.collect{|topic| [topic.name, topic.name]}, {:prompt => 'Any', :selected => params[:topic]}, :onchange => 'tagged_questions();', :style => 'width:100px;') %>
        </th>
        <th>
          <a class="btn btn-primary" href="/questions/new">Add</a>
        </th>
      </tr>
      <tr>
        <th>Questions</th>
        <th>Complexity</th>
        <th>Topic</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td>
            <%= question.title %>
            <br/><i style="color:#aaa;"> by <%=question.submitter%></i>
          </td>
          <td>
            <%= question.complexity %>
          </td>
          <td>
            <%= question.topic %>
          </td>
          <td>
            <button class="btn" onclick="window.location = '/questions/<%=question.id%>/edit';">Edit</button>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @questions %>

<div class="well" style="min-height:40px;">
  <div style="float:left">
    <!-- question upload starts -->
    <%= raw render_upload_status %>
    <span id="upload_form_container">Import questions <a href="#"> e.g. template.xls</a>
      <%= form_tag '/questions/import', :multipart => true, :onsubmit => 'upload_started();' do %>
        <%= file_field_tag :questions_file %>
        <%= submit_tag 'Upload', :class => 'btn btn-primary', :style => 'margin-bottom:10px;' %>
      <% end %>
    </span>
    <span id="uploading" style="display: none;">
      Uploading.....     please wait.
    </span>

    <script type="text/javascript">
      $('#upload_form_container').popover({
        content:  "<br/>1. Only .xls file is allowed \
                   <br/>2. Upto 10 MB allowed \
                   <br/>3. Please find the template for upload <a href=\"/assets/questions_imported/questions_import_template.xls\">here</a> \
                   <br/>4. Formulas and functions (for.e.g \"=sum(A1,A2)\", \"=concat(A1,A2)\") are not allowed "
      });


      function upload_started(){
        $('upload_form_container').style.display = 'none';
        $('uploading').style.display = 'block';
        show_spinner('spinner');
        return true;
      }
    </script>
    <!-- question upload ends -->
  </div>

  <div style="float:right;padding-top:30px;">
    <p>
      Download
      <a href="#" onclick="window.location = window.location + '?format=text'">TXT</a>
      | <a href="#" onclick="window.location = window.location + '?format=csv'">CSV</a>
    </p>
  </div>
</div>



<script type="text/javascript">
  function tagged_questions(tags){
    if (!tags)
      tags = [];

    if ($("#question_search").val())
      tags.push("search="+$("#question_search").val());

    if ($("#question_complexity_list").val())
      tags.push("complexity="+$("#question_complexity_list").val());

    if ($("#question_topic_list").val())
      tags.push("topic=" + $("#question_topic_list").val());

    query = "";

    if (tags.length>0)
      query += "?";

    for(var i=0; i<tags.length; i++){
      query += tags[i] + "&";
    }

    window.location = "/questions" + query;
  }
</script>

app/views/questions/new.html.erb
<div class="control-group">
  <div class="controls">
    <h4 style="color: #444;margin-left: 160px;">Adding a new question</h4>
  </div>
</div>
<br/>

<%= render :partial => 'form', :locals => { :form_action_title => 'New' } %>

app/views/questions/show.html.erb
<h3>Question: </h3>

<div class="well">
  <p>
    <%= @question.title %>
    <br/><i>by <%=@question.submitter.email%></i>
  </p>
  <p>
    <%= @question.statement.html_safe %>
  </p>
  <p>
    Complexity: <%= @question.complexity %>
  </p>
  <p>
    Topic: <%= @question.topic %>
  </p>
  <p>
    <%= raw attachments_show @question %>
  </p>

</div>

<p>
  <%= link_to "Edit", edit_question_path(@question), :class => 'btn' %> |
  <%= link_to "Destroy", @question, :confirm => 'Are you sure?', :method => :delete, :class => 'btn' %> |
  <%= link_to "View All", questions_path, :class => 'btn btn-danger' %>
</p>